### ISSUE TITLE
Future direction?

### ISSUE THREAD

**Issue by rnewman** [zshipko/rust-kv#1]
Hello!

Coincidentally, I have also been working on a wrapper around LMDB.

I've spent some time working on things that I don't yet see represented here:

- Correctly restrict to one handle per process via a 'manager'.
- Integer-keyed LMDB stores.
- Key-typed generic stores, so if you want a store keyed off URIs or integers only, Rust will enforce your constraint.
- More detailed error wrapping via `failure`.
- Encoding and decoding of values via `bincode`/`serde`, so it can handle storage of almost any serializable object.
- Tagging of types so we know which deserialization to apply.

Naturally I'd like to avoid wasted effort in any direction, and either merge some features, use existing libraries as layers, or clarify design decisions.

What's your plan for the future of your library? Do you see it as relatively stable as is (that is, you're already meeting your own needs), or are you hoping to grow it into something more substantial?

**Comment by rnewman** [comment]
[Here's a pointer](https://github.com/mozilla-prototypes/rkv), btw.

**Comment by zshipko** [comment]
Hey @rnewman, sorry for the slow reply.

I have just recently started developing this library to serve the needs of another group of projects -- I wouldn't call it stable but I am moving slowly and trying to avoid pulling in a huge amount of dependencies right away. 

Support for integer keys, and serde integration are two things I'm considering in terms of next steps. I am not interested in making any decisions regarding serialization formats and have been looking at implementing key constraints at the `Database/Bucket` level rather than at the `Store` level, though that would still allow for some type-sloppiness. As I said above, this is used by a group of projects all with different needs storage-wise, some of them use different databases for different types of data. Your concept of a manger is very nice and I hadn't considered implementing something like that for `kv`. Perhaps I could port the downstream applications to use different stores for different key types instead.

Let me know what you had in mind in terms of working together, I am definitely open to combining efforts. I was planning on implementing a few of the things I mentioned above this week. Maybe at that point the projects will be slightly more similar any easier to merge?

**Comment by zshipko** [comment]
I hope it's okay that I've ported your manager code, see [manager.rs](https://github.com/zshipko/rust-kv/blob/master/src/manager.rs)

I've also added some of the features mentioned above, but am still working on cleaning things up a bit.

**Comment by rnewman** [comment]
> I hope it's okay that I've ported your manager code, see manager.rs

Sure! So long as the licenses are compatible, that's totally fine.

> Let me know what you had in mind in terms of working together, I am definitely open to combining efforts. I was planning on implementing a few of the things I mentioned above this week. Maybe at that point the projects will be slightly more similar any easier to merge?

Mozilla is likely to continue investing in this area, and `rkv` is the first step I took on that path. I'm not sure yet which approach to combining efforts makes most sense as we scale up the number of engineers working on it, and start to tackle things like idiomatic Android and iOS integration, but it does seem like there's overlap!

**Comment by zshipko** [comment]
Ah I didn't quite realize this is a semi-official Mozilla project! I will keep up with developments on `rkv` and do my best to contribute. Feel free to let me know once `rkv` is ramping up and I am happy to get more involved if you need some additional help.

If it makes most sense to pour all efforts into `rkv` then I can get on board with that, but for now I will continue to develop `kv`.

Let's definitely not close the door on combining efforts, but perhaps we should wait for both `kv` and `rkv` to be developed further, since there is no real consequence to having both at the moment (other than some slight code duplication).
