### ISSUE TITLE
Questions: Performance Review and Custom Serde Serialization Schemes

### ISSUE THREAD

**Issue by SilentCicero** [zshipko/rust-kv#18]
Hi, awesome work with Kv,

Was looking for a simplified interface to Sled, so this is cool.

**Performance:**
Can you expand on why you chose Sled, did you do any performance benchmarks against Rocks or LMDB before this?

Anything you uncovered?

**Custom Encoding / Serialization:**
Any pathway for me to integrate a custom serde encoder/decoder?

I have a scheme I want to use that isn't listed, for encoding / decoding keys.

Awesome work, happy holidays.

**Comment by zshipko** [comment]
Thanks!

The goal of this crate is to provide a basic interface without performance being a huge concern.

kv used to be based on lmdb but I moved over to sled because the lmdb crate had some issues and wasn’t really being maintained at the time. I also like not having that external dependency.

It could be possible to make a `Storage` trait that allows for multiple backends but I think in a situation where performance is crucial a more specialized implementation would be more efficient.

For other encodings that aren’t listed in the README you would need to implement the [Codec](https://docs.rs/kv/0.22.0/kv/trait.Codec.html) trait. [Here](https://github.com/zshipko/rust-kv/blob/master/src/codec.rs#L62) is an example. If you have something that you think might be helpful for other people then definitely submit a PR!
